#!/usr/bin/env python
# -*- coding: utf8 -*-

dic = {"フシギダネ" : "Bulbasaur",
    "フシギソウ" : "Ivysaur",
    "フシギバナ" : "Venusaur",
    "ヒトカゲ" : "Charmander",
    "リザード" : "Charmeleon",
    "リザードン" : "Charizard",
    "ゼニガメ" : "Squirtle",
    "カメール" : "Wartortle",
    "カメックス" : "Blastoise",
    "キャタピー" : "Caterpie",
    "トランセル" : "Metapod",
    "バタフリー" : "Butterfree",
    "ビードル" : "Weedle",
    "コクーン" : "Kakuna",
    "スピアー" : "Beedrill",
    "ポッポ" : "Pidgey",
    "ピジョン" : "Pidgeotto",
    "ピジョット" : "Pidgeot",
    "コラッタ" : "Rattata",
    "ラッタ" : "Raticate",
    "オニスズメ" : "Spearow",
    "オニドリル" : "Fearow",
    "アーボ" : "Ekans",
    "アーボック" : "Arbok",
    "ピカチュウ" : "Pikachu",
    "ライチュウ" : "Raichu",
    "サンド" : "Sandshrew",
    "サンドパン" : "Sandslash",
    "ニドラン♀" : "Nidoran♀",
    "ニドリーナ" : "Nidorina",
    "ニドクイン" : "Nidoqueen",
    "ニドラン♂" : "Nidoran♂",
    "ニドリーノ" : "Nidorino",
    "ニドキング" : "Nidoking",
    "ピッピ" : "Clefairy",
    "ピクシー" : "Clefable",
    "ロコン" : "Vulpix",
    "キュウコン" : "Ninetales",
    "プリン" : "Jigglypuff",
    "プクリン" : "Wigglytuff",
    "ズバット" : "Zubat",
    "ゴルバット" : "Golbat",
    "ナゾノクサ" : "Oddish",
    "クサイハナ" : "Gloom",
    "ラフレシア" : "Vileplume",
    "パラス" : "Paras",
    "パラセクト" : "Parasect",
    "コンパン" : "Venonat",
    "モルフォン" : "Venomoth",
    "ディグダ" : "Diglett",
    "ダグトリオ" : "Dugtrio",
    "ニャース" : "Meowth",
    "ペルシアン" : "Persian",
    "コダック" : "Psyduck",
    "ゴルダック" : "Golduck",
    "マンキー" : "Mankey",
    "オコリザル" : "Primeape",
    "ガーディ" : "Growlithe",
    "ウインディ" : "Arcanine",
    "ニョロモ" : "Poliwag",
    "ニョロゾ" : "Poliwhirl",
    "ニョロボン" : "Poliwrath",
    "ケーシィ" : "Abra",
    "ユンゲラー" : "Kadabra",
    "フーディン" : "Alakazam",
    "ワンリキー" : "Machop",
    "ゴーリキー" : "Machoke",
    "カイリキー" : "Machamp",
    "マダツボミ" : "Bellsprout",
    "ウツドン" : "Weepinbell",
    "ウツボット" : "Victreebel",
    "メノクラゲ" : "Tentacool",
    "ドククラゲ" : "Tentacruel",
    "イシツブテ" : "Geodude",
    "ゴローン" : "Graveler",
    "ゴローニャ" : "Golem",
    "ポニータ" : "Ponyta",
    "ギャロップ" : "Rapidash",
    "ヤドン" : "Slowpoke",
    "ヤドラン" : "Slowbro",
    "コイル" : "Magnemite",
    "レアコイル" : "Magneton",
    "カモネギ" : "Farfetch'd",
    "ドードー" : "Doduo",
    "ドードリオ" : "Dodrio",
    "パウワウ" : "Seel",
    "ジュゴン" : "Dewgong",
    "ベトベター" : "Grimer",
    "ベトベトン" : "Muk",
    "シェルダー" : "Shellder",
    "パルシェン" : "Cloyster",
    "ゴース" : "Gastly",
    "ゴースト" : "Haunter",
    "ゲンガー" : "Gengar",
    "イワーク" : "Onix",
    "スリープ" : "Drowzee",
    "スリーパー" : "Hypno",
    "クラブ" : "Krabby",
    "キングラー" : "Kingler",
    "ビリリダマ" : "Voltorb",
    "マルマイン" : "Electrode",
    "タマタマ" : "Exeggcute",
    "ナッシー" : "Exeggutor",
    "カラカラ" : "Cubone",
    "ガラガラ" : "Marowak",
    "サワムラー" : "Hitmonlee",
    "エビワラー" : "Hitmonchan",
    "ベロリンガ" : "Lickitung",
    "ドガース" : "Koffing",
    "マタドガス" : "Weezing",
    "サイホーン" : "Rhyhorn",
    "サイドン" : "Rhydon",
    "ラッキー" : "Chansey",
    "モンジャラ" : "Tangela",
    "ガルーラ" : "Kangaskhan",
    "タッツー" : "Horsea",
    "シードラ" : "Seadra",
    "トサキント" : "Goldeen",
    "アズマオウ" : "Seaking",
    "ヒトデマン" : "Staryu",
    "スターミー" : "Starmie",
    "バリヤード" : "Mr. Mime",
    "ストライク" : "Scyther",
    "ルージュラ" : "Jynx",
    "エレブー" : "Electabuzz",
    "ブーバー" : "Magmar",
    "カイロス" : "Pinsir",
    "ケンタロス" : "Tauros",
    "コイキング" : "Magikarp",
    "ギャラドス" : "Gyarados",
    "ラプラス" : "Lapras",
    "メタモン" : "Ditto",
    "イーブイ" : "Eevee",
    "シャワーズ" : "Vaporeon",
    "サンダース" : "Jolteon",
    "ブースター" : "Flareon",
    "ポリゴン" : "Porygon",
    "オムナイト" : "Omanyte",
    "オムスター" : "Omastar",
    "カブト" : "Kabuto",
    "カブトプス" : "Kabutops",
    "プテラ" : "Aerodactyl",
    "カビゴン" : "Snorlax",
    "フリーザー" : "Articuno",
    "サンダー" : "Zapdos",
    "ファイヤー" : "Moltres",
    "ミニリュウ" : "Dratini",
    "ハクリュー" : "Dragonair",
    "カイリュー" : "Dragonite",
    "ミュウツー" : "Mewtwo",
    "ミュウ" : "Mew"}

# ハングル
han = ["이상해씨",
"이상해풀",
"이상해꽃",
"파이리",
"리자드",
"리자몽",
"꼬부기",
"어니부기",
"거북왕",
"캐터피",
"단데기",
"버터플",
"뿔충이",
"딱충이",
"독침붕",
"구구",
"피죤",
"피죤투",
"꼬렛",
"레트라",
"깨비참",
"깨비드릴조",
"아보",
"아보크",
"피카츄",
"라이츄",
"모래두지",
"고지",
"니드런♀",
"니드리나",
"니드퀸",
"니드런♂",
"니드리노",
"니드킹",
"삐삐",
"픽시",
"식스테일",
"나인테일",
"푸린",
"푸크린",
"주뱃",
"골뱃",
"뚜벅쵸",
"냄새꼬",
"라플레시아",
"파라스",
"파라섹트",
"콘팡",
"도나리",
"디그다",
"닥트리오",
"나옹",
"페르시온",
"고라파덕",
"골덕",
"망키",
"성원숭",
"가디",
"윈디",
"발챙이",
"수륙챙이",
"강챙이",
"캐이시",
"윤겔라",
"후딘",
"알통몬",
"근육몬",
"괴력몬",
"모다피",
"우츠동",
"우츠보트",
"왕눈해",
"독파리",
"꼬마돌",
"데구리",
"딱구리",
"포니타",
"날쌩마",
"야돈",
"야도란",
"코일",
"레어코일",
"파오리",
"두두",
"두트리오",
"쥬쥬",
"쥬레곤",
"질퍽이",
"질뻐기",
"셀러",
"파르셀",
"고오스",
"고우스트",
"팬텀",
"롱스톤",
"슬리프",
"슬리퍼",
"크랩",
"킹크랩",
"찌리리공",
"붐볼",
"아라리",
"나시",
"탕구리",
"텅구리",
"시라소몬",
"홍수몬",
"내루미",
"또가스",
"또도가스",
"뿔카노",
"코뿌리",
"럭키",
"덩구리",
"캥카",
"쏘드라",
"시드라",
"콘치",
"왕콘치",
"별가사리",
"아쿠스타",
"마임맨",
"스라크",
"루주라",
"에레브",
"마그마",
"쁘사이저",
"켄타로스",
"잉어킹",
"갸라도스",
"라프라스",
"메타몽",
"이브이",
"샤미드",
"쥬피썬더",
"부스터",
"폴리곤",
"암나이트",
"암스타",
"투구",
"투구푸스",
"프테라",
"잠만보",
"프리져",
"썬더",
"파이어",
"미뇽",
"신뇽",
"망나뇽",
"뮤츠",
"뮤"]

# key反転
mydict_inv = {v:k for k, v in dic.items()}

# 値をハングル化
mydict_inv = {k:han.pop() for k, v in mydict_inv.items()}

arr = ["Abra","Aerodactyl","Alakazam","Arbok","Arcanine","Articuno","Beedrill","Bellsprout","Blastoise","Bulbasaur","Butterfree","Caterpie","Chansey","Charizard","Charmander","Charmeleon","Clefable","Clefairy","Cloyster","Cubone","Dewgong","Diglett","Ditto","Dodrio","Doduo","Dragonair","Dragonite","Dratini","Drowzee","Dugtrio","Eevee","Ekans","Electabuzz","Electrode","Exeggcute","Exeggutor","Farfetch'd","Fearow","Flareon","Gastly","Gengar","Geodude","Gloom","Golbat","Goldeen","Golduck","Golem","Graveler","Grimer","Growlithe","Gyarados","Haunter","Hitmonchan","Hitmonlee","Horsea","Hypno","Ivysaur","Jigglypuff","Jolteon","Jynx","Kabuto","Kabutops","Kadabra","Kakuna","Kangaskhan","Kingler","Koffing","Krabby","Lapras","Lickitung","Machamp","Machoke","Machop","Magikarp","Magmar","Magnemite","Magneton","Mankey","Marowak","Meowth","Metapod","Mew","Mewtwo","Moltres","Mr. Mime","Muk","Nidoking","Nidoqueen","Nidoran♀","Nidoran♂","Nidorina","Nidorino","Ninetales","Oddish","Omanyte","Omastar","Onix","Paras","Parasect","Persian","Pidgeot","Pidgeotto","Pidgey","Pikachu","Pinsir","Poliwag","Poliwhirl","Poliwrath","Ponyta","Porygon","Primeape","Psyduck","Raichu","Rapidash","Raticate","Rattata","Rhydon","Rhyhorn","Sandshrew","Sandslash","Scyther","Seadra","Seaking","Seel","Shellder","Slowbro","Slowpoke","Snorlax","Spearow","Squirtle","Starmie","Staryu","Tangela","Tauros","Tentacool","Tentacruel","Vaporeon","Venomoth","Venonat","Venusaur","Victreebel","Vileplume","Voltorb","Vulpix","Wartortle","Weedle","Weepinbell","Weezing","Wigglytuff","Zapdos","Zubat"]

for item in arr:
    print("\"" + mydict_inv[item] + "\",")
